version: "3.9"

services:
  bn:
    container_name: bn
    image: sigp/lighthouse:latest-modern
    ports:
      # - "9000:9000/tcp"
      # - "9000:9000/udp"
      - "5052:5052"
    volumes:
      - $HOME/.lighthouse:/root/.lighthouse
    command: 'lighthouse beacon --http --http-address 0.0.0.0'
